### ISSUE TITLE
No password asked during bitmask email account creation

### ISSUE THREAD

**Issue by buzzworkers** [leapcode/bitmask_thunderbird#10]
Error with ID or password, the configuration cannot be verified. 

the wizard is not asking the password of the account, hence impossible to complete the steps
using thunderbird/linux

when i click finish, i get a popup saying : Missing error string
and below : user_pass_invalid

**Comment by meskio** [comment]
Thunderbird don't need to know your bitmask password, it connects to a local IMAP server setted up by bitmask and any password is accepted (we plan to change that in the future to generate some random passwords). That is why thunderbird plugin don't ask for passwords.

But still it looks like you have triggered an error. My guess is that you are using bitmask with a provider that don't support email (there is no public providers with email yet). Can that be your issue? Still the error is too obscure, we should find a way to give more useful feedback to the user about not having email enabled.

We are close to release an alpha version of email and we will be happy to get testers to use it.

Thank you for your report.

**Comment by meskio** [comment]
I created an issue in our chili related to that:
https://leap.se/code/issues/6786
